L3_interfaces:
  - interface_type: Ethernet
    interface_id: 0/0
    description: ISP
    ip_address: 155.1.48.1
    mask: 255.255.255.252
  - interface_type: Ethernet
    interface_id: 0/1
    description: Router to Router link
    ip_address: 172.16.2.2
    mask: 255.255.255.252
  - interface_type: Ethernet
    interface_id: 0/2
    description: MGMT
    ip_address: 10.2.1.3
    mask: 255.255.255.0
  - interface_type: Ethernet
    interface_id: 0/2.10
    encapsulation: 10
    description: Guest
    ip_address: 10.2.10.3
    mask: 255.255.255.0
  - interface_type: Ethernet
    interface_id: 0/2.20
    encapsulation: 20
    description: data
    ip_address: 10.2.20.3
    mask: 255.255.255.0
  - interface_type: Ethernet
    interface_id: 0/2.30
    encapsulation: 30
    description: voice
    ip_address: 10.2.30.3
    mask: 255.255.255.0
static_routes:
  - subnet: 0.0.0.0
    mask: 0.0.0.0
    next_hop_ip: 155.1.48.2
ip_slas:
  - number: 1
    tracked_ip: 155.1.48.2
    frequency: 3000
    timeout: 2000
    threshold: 1000
    track_number: 1

