- name: configure eigrp
  ios_config:
    src: "eigrp.j2"
  register: pushed_config
  notify: save_config

- name: display_ip_sla_pushed_config
  debug: var=pushed_config.updates
  when: pushed_config.changed
